backend:
  name: github
  repo: ZeeshaanMaudar/firstGatsbyApp

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: Create At, name: date, widget: date}
      - {label: Post, name: body, widget: markdown}